name: Weekly Data Update

on:
  schedule:
    - cron: "0 0 * * 1" # Every Monday at 00:00 UTC
  workflow_dispatch:

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTOMATED_UPDATE_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        run: |
          cd src
          python update_data.py

      - name: Commit changes
        run: |
          git config --global user.name 'Automated Update'
          git config --global user.email 'actions@users.noreply.github.com'
          git add src/hsr_dataset.json
          git add src/dataset_archive/*.json  # Add this line to commit archived datasets
          git add src/dataset_archive/.gitkeep  # Preserve directory structure
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated weekly data update"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.AUTOMATED_UPDATE_PAT }}
          branch: main
