name: Weekly Data Update

on:
  schedule:
    - cron: "0 0 * * 1" # Every Monday at 00:00 UTC
  workflow_dispatch: # Allow manual triggers

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          token: ${{ secrets.AUTOMATED_UPDATE_PAT }} # Use PAT here
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run update script
        run: |
          cd src
          python update_data.py

      - name: Commit updated data
        env:
          PAT: ${{ secrets.AUTOMATED_UPDATE_PAT }}
        run: |
          git config --global user.name 'Automated Update'
          git config --global user.email 'actions@users.noreply.github.com'
          git add src/hsr_dataset.json
          git commit -m "Automated weekly data update" || echo "No changes to commit"
          git push https://${{ secrets.AUTOMATED_UPDATE_PAT }}@github.com/$GITHUB_REPOSITORY.git HEAD:main
